version: '2'
networks:
  micronet:
services:
  consul1:
    image: gliderlabs/consul
    container_name: consul1
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:8600/udp"
    networks:
      - micronet
    command: ["agent", "-server", "-bootstrap-expect=1", "-data-dir=/tmp/consul", "-node=consul1", "-client=0.0.0.0", "-ui"]

  configurationserver1:
    image: antifragilesoftware/simple-boot-configuration-server
    container_name: configurationserver1
    ports:
     - "8888:8888"
    depends_on:
     - consul1
    networks:
      - micronet
    command: ["java","--spring.cloud.consul.host=consul1","-Djava.security.egd=file:/dev/./urandom","-jar","/microservice.jar"]

  configurationserver2:
    image: antifragilesoftware/simple-boot-configuration-server
    container_name: configurationserver2
    ports:
     - "8889:8888"
    depends_on:
     - consul1
    networks:
      - micronet
    command: ["java","--spring.cloud.consul.host=consul1","-Djava.security.egd=file:/dev/./urandom","-jar","/microservice.jar"]
