version: '2'
networks:
  micronet:
services:
  consul1:
    image: gliderlabs/consul
    container_name: consul1
    ports:
     - "8400:8400"
     - "8500:8500"
     - "8600:8600/udp"
    networks:
      - micronet
    command: ["agent", "-server", "-bootstrap-expect=1", "-data-dir=/tmp/consul", "-node=consul1", "-client=0.0.0.0", "-ui"]

  configurationserver1:
    image: antifragilesoftware/simple-boot-configuration-server
    container_name: configurationserver
    ports:
     - "8080:8080"
    depends_on:
     - consul1
    networks:
      - micronet
    command: ["java","--eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka/","--eureka.instance.prefer-ip-address=true","-Djava.security.egd=file:/dev/./urandom","-jar","/microservice.jar"]